CREATE TABLE WATCH_CATALOG
(
    ID                SERIAL PRIMARY KEY,
    NAME              VARCHAR(60) NOT NULL,
    UNIT_PRICE        INT         NOT NULL,
    DISCOUNT_QUANTITY INT DEFAULT 1,
    DISCOUNT_FACTOR   DECIMAL DEFAULT 1,
    CONSTRAINT DISCOUNT_FACTOR_CONSTRAINT CHECK (DISCOUNT_FACTOR >= 1)
) INSERT INTO
    WATCH_CATALOG (NAME, UNIT_PRICE, DISCOUNT_QUANTITY, DISCOUNT_PRICE)
VALUES
    ('Rolex', 100, 3, 0.33)
    ('Michael Kors', 80, 2, 0.25)
    ('Swatch', 50, null, null)
    ('Casio', 30, null, null)

